// Mocks generated by Mockito 5.4.6 from annotations
// in novelty/test/providers/novel_info_offline_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:drift/drift.dart' as _i2;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:narou_parser/narou_parser.dart' as _i19;
import 'package:novelty/database/database.dart' as _i3;
import 'package:novelty/models/download_progress.dart' as _i18;
import 'package:novelty/models/download_result.dart' as _i11;
import 'package:novelty/models/episode.dart' as _i7;
import 'package:novelty/models/novel_download_summary.dart' as _i13;
import 'package:novelty/models/novel_info.dart' as _i6;
import 'package:novelty/models/novel_search_query.dart' as _i14;
import 'package:novelty/models/novel_search_result.dart' as _i8;
import 'package:novelty/repositories/novel_repository.dart' as _i15;
import 'package:novelty/services/api_service.dart' as _i9;
import 'package:novelty/utils/settings_provider.dart' as _i17;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i16;
import 'package:riverpod_swr/riverpod_swr.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_1 extends _i1.SmartFake
    implements _i3.$AppDatabaseManager {
  _Fake$AppDatabaseManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$NovelsTable_2 extends _i1.SmartFake implements _i3.$NovelsTable {
  _Fake$NovelsTable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$LibraryEntriesTable_3 extends _i1.SmartFake
    implements _i3.$LibraryEntriesTable {
  _Fake$LibraryEntriesTable_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ReadingHistoryTable_4 extends _i1.SmartFake
    implements _i3.$ReadingHistoryTable {
  _Fake$ReadingHistoryTable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$EpisodeEntitiesTable_5 extends _i1.SmartFake
    implements _i3.$EpisodeEntitiesTable {
  _Fake$EpisodeEntitiesTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_6 extends _i1.SmartFake
    implements _i2.GeneratedDatabase {
  _FakeGeneratedDatabase_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_7 extends _i1.SmartFake
    implements _i2.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_8 extends _i1.SmartFake
    implements _i2.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_9 extends _i1.SmartFake
    implements _i2.DatabaseConnection {
  _FakeDatabaseConnection_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_10 extends _i1.SmartFake implements _i2.QueryExecutor {
  _FakeQueryExecutor_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_11 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_12 extends _i1.SmartFake
    implements _i2.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_13 extends _i1.SmartFake implements _i2.Migrator {
  _FakeMigrator_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_14<T> extends _i1.SmartFake implements _i5.Future<T> {
  _FakeFuture_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_15<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.InsertStatement<T1, D1> {
  _FakeInsertStatement_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_16<T extends _i2.Table, D> extends _i1.SmartFake
    implements _i2.UpdateStatement<T, D> {
  _FakeUpdateStatement_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_17<T1 extends _i2.HasResultSet, D>
    extends _i1.SmartFake
    implements _i2.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_18<FirstT extends _i2.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i2.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_19<Row> extends _i1.SmartFake
    implements _i2.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_20<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_21<T> extends _i1.SmartFake implements _i2.Selectable<T> {
  _FakeSelectable_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_22 extends _i1.SmartFake
    implements _i2.GenerationContext {
  _FakeGenerationContext_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNovelInfo_23 extends _i1.SmartFake implements _i6.NovelInfo {
  _FakeNovelInfo_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEpisode_24 extends _i1.SmartFake implements _i7.Episode {
  _FakeEpisode_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNovelSearchResult_25 extends _i1.SmartFake
    implements _i8.NovelSearchResult {
  _FakeNovelSearchResult_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiService_26 extends _i1.SmartFake implements _i9.ApiService {
  _FakeApiService_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSwrClient_27 extends _i1.SmartFake implements _i10.SwrClient {
  _FakeSwrClient_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDownloadResult_28 extends _i1.SmartFake
    implements _i11.DownloadResult {
  _FakeDownloadResult_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i3.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i2.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_0(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i2.MigrationStrategy);

  @override
  _i3.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_1(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i3.$AppDatabaseManager);

  @override
  _i3.$NovelsTable get novels =>
      (super.noSuchMethod(
            Invocation.getter(#novels),
            returnValue: _Fake$NovelsTable_2(this, Invocation.getter(#novels)),
          )
          as _i3.$NovelsTable);

  @override
  _i3.$LibraryEntriesTable get libraryEntries =>
      (super.noSuchMethod(
            Invocation.getter(#libraryEntries),
            returnValue: _Fake$LibraryEntriesTable_3(
              this,
              Invocation.getter(#libraryEntries),
            ),
          )
          as _i3.$LibraryEntriesTable);

  @override
  _i3.$ReadingHistoryTable get readingHistory =>
      (super.noSuchMethod(
            Invocation.getter(#readingHistory),
            returnValue: _Fake$ReadingHistoryTable_4(
              this,
              Invocation.getter(#readingHistory),
            ),
          )
          as _i3.$ReadingHistoryTable);

  @override
  _i3.$EpisodeEntitiesTable get episodeEntities =>
      (super.noSuchMethod(
            Invocation.getter(#episodeEntities),
            returnValue: _Fake$EpisodeEntitiesTable_5(
              this,
              Invocation.getter(#episodeEntities),
            ),
          )
          as _i3.$EpisodeEntitiesTable);

  @override
  Iterable<_i2.TableInfo<_i2.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i2.TableInfo<_i2.Table, Object?>>[],
          )
          as Iterable<_i2.TableInfo<_i2.Table, Object?>>);

  @override
  List<_i2.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i2.DatabaseSchemaEntity>[],
          )
          as List<_i2.DatabaseSchemaEntity>);

  @override
  _i2.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_6(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.GeneratedDatabase);

  @override
  _i2.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_7(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i2.DriftDatabaseOptions);

  @override
  _i2.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_8(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i2.StreamQueryUpdateRules);

  @override
  _i2.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_9(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i2.DatabaseConnection);

  @override
  _i2.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i12.dummyValue<_i2.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i2.SqlTypes);

  @override
  _i2.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_10(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i2.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_11(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_12(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i2.DatabaseConnectionUser);

  @override
  _i5.Future<_i3.Novel?> getNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#getNovel, [ncode]),
            returnValue: _i5.Future<_i3.Novel?>.value(),
          )
          as _i5.Future<_i3.Novel?>);

  @override
  _i5.Stream<_i3.Novel?> watchNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchNovel, [ncode]),
            returnValue: _i5.Stream<_i3.Novel?>.empty(),
          )
          as _i5.Stream<_i3.Novel?>);

  @override
  _i5.Future<List<_i3.Novel>> searchNovels(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchNovels, [query]),
            returnValue: _i5.Future<List<_i3.Novel>>.value(<_i3.Novel>[]),
          )
          as _i5.Future<List<_i3.Novel>>);

  @override
  _i5.Future<List<_i3.EpisodeSearchResult>> searchEpisodes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchEpisodes, [query]),
            returnValue: _i5.Future<List<_i3.EpisodeSearchResult>>.value(
              <_i3.EpisodeSearchResult>[],
            ),
          )
          as _i5.Future<List<_i3.EpisodeSearchResult>>);

  @override
  _i5.Future<void> ensureNovelExists(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#ensureNovelExists, [ncode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> addToLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#addToLibrary, [ncode]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> removeFromLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromLibrary, [ncode]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.Novel>> getLibraryNovels() =>
      (super.noSuchMethod(
            Invocation.method(#getLibraryNovels, []),
            returnValue: _i5.Future<List<_i3.Novel>>.value(<_i3.Novel>[]),
          )
          as _i5.Future<List<_i3.Novel>>);

  @override
  _i5.Stream<List<_i3.LibraryNovelEntry>> watchLibraryNovels() =>
      (super.noSuchMethod(
            Invocation.method(#watchLibraryNovels, []),
            returnValue: _i5.Stream<List<_i3.LibraryNovelEntry>>.empty(),
          )
          as _i5.Stream<List<_i3.LibraryNovelEntry>>);

  @override
  _i5.Future<bool> isInLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#isInLibrary, [ncode]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Stream<bool> watchIsInLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchIsInLibrary, [ncode]),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Future<void> markNarouBookmarkSynced(
    String? ncode, {
    String? useridFavncode,
    String? favToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markNarouBookmarkSynced,
              [ncode],
              {#useridFavncode: useridFavncode, #favToken: favToken},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.NarouFavToken?> getNarouFavToken(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#getNarouFavToken, [ncode]),
            returnValue: _i5.Future<_i3.NarouFavToken?>.value(),
          )
          as _i5.Future<_i3.NarouFavToken?>);

  @override
  _i5.Future<bool> isNarouBookmarkSynced(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#isNarouBookmarkSynced, [ncode]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> insertNovel(_i3.NovelsCompanion? novel) =>
      (super.noSuchMethod(
            Invocation.method(#insertNovel, [novel]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> addToHistory(_i3.ReadingHistoryCompanion? history) =>
      (super.noSuchMethod(
            Invocation.method(#addToHistory, [history]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.HistoryData>> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: _i5.Future<List<_i3.HistoryData>>.value(
              <_i3.HistoryData>[],
            ),
          )
          as _i5.Future<List<_i3.HistoryData>>);

  @override
  _i5.Stream<List<_i3.HistoryData>> watchHistory() =>
      (super.noSuchMethod(
            Invocation.method(#watchHistory, []),
            returnValue: _i5.Stream<List<_i3.HistoryData>>.empty(),
          )
          as _i5.Stream<List<_i3.HistoryData>>);

  @override
  _i5.Future<int> deleteHistory(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHistory, [ncode]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> clearHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearHistory, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i3.ReadingHistoryData?> getReadingHistoryByNcode(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#getReadingHistoryByNcode, [ncode]),
            returnValue: _i5.Future<_i3.ReadingHistoryData?>.value(),
          )
          as _i5.Future<_i3.ReadingHistoryData?>);

  @override
  _i5.Future<void> upsertEpisodes(
    List<_i3.EpisodeEntitiesCompanion>? newEpisodes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertEpisodes, [newEpisodes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateEpisodeContent(
    _i3.EpisodeEntitiesCompanion? episode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEpisodeContent, [episode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.EpisodeRow?> getEpisodeData(String? ncode, int? episodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getEpisodeData, [ncode, episodeId]),
            returnValue: _i5.Future<_i3.EpisodeRow?>.value(),
          )
          as _i5.Future<_i3.EpisodeRow?>);

  @override
  _i5.Future<List<_i7.Episode>> getEpisodes(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#getEpisodes, [ncode]),
            returnValue: _i5.Future<List<_i7.Episode>>.value(<_i7.Episode>[]),
          )
          as _i5.Future<List<_i7.Episode>>);

  @override
  _i5.Future<List<_i7.Episode>> getEpisodesRange(
    String? ncode,
    int? start,
    int? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEpisodesRange, [ncode, start, end]),
            returnValue: _i5.Future<List<_i7.Episode>>.value(<_i7.Episode>[]),
          )
          as _i5.Future<List<_i7.Episode>>);

  @override
  _i5.Stream<List<_i7.Episode>> watchEpisodesRange(
    String? ncode,
    int? start,
    int? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchEpisodesRange, [ncode, start, end]),
            returnValue: _i5.Stream<List<_i7.Episode>>.empty(),
          )
          as _i5.Stream<List<_i7.Episode>>);

  @override
  _i5.Stream<_i3.EpisodeRow?> watchEpisodeEntity(
    String? ncode,
    int? episodeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchEpisodeEntity, [ncode, episodeId]),
            returnValue: _i5.Stream<_i3.EpisodeRow?>.empty(),
          )
          as _i5.Stream<_i3.EpisodeRow?>);

  @override
  _i5.Stream<List<_i13.NovelDownloadSummary>> watchDownloadingNovels() =>
      (super.noSuchMethod(
            Invocation.method(#watchDownloadingNovels, []),
            returnValue: _i5.Stream<List<_i13.NovelDownloadSummary>>.empty(),
          )
          as _i5.Stream<List<_i13.NovelDownloadSummary>>);

  @override
  _i5.Stream<List<_i13.NovelDownloadSummary>> watchCompletedDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#watchCompletedDownloads, []),
            returnValue: _i5.Stream<List<_i13.NovelDownloadSummary>>.empty(),
          )
          as _i5.Stream<List<_i13.NovelDownloadSummary>>);

  @override
  _i2.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_13(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i2.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i2.QueryExecutor? executor,
    _i2.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Ret> computeWithDatabase<Ret, DB extends _i2.GeneratedDatabase>({
    required _i5.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i2.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i5.Future<Ret>.value(v),
                ) ??
                _FakeFuture_14<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
          )
          as _i5.Future<Ret>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i5.Stream<T>.empty(),
          )
          as _i5.Stream<T>);

  @override
  T alias<T, D>(_i2.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i12.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<Set<_i2.TableUpdate>> tableUpdates([
    _i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i5.Stream<Set<_i2.TableUpdate>>.empty(),
          )
          as _i5.Stream<Set<_i2.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
    _i5.FutureOr<T> Function(_i2.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_14<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i5.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_15<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
    _i2.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_16<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_17<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_18<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
    Iterable<_i2.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_19<_i2.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_20<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i2.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<List<_i2.QueryRow>>.value(<_i2.QueryRow>[]),
          )
          as _i5.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_21<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_21<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_14<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_14<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i2.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i12.ifNotNull(
                  _i12.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_14<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_22(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_22(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i9.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, _i6.NovelInfo>> fetchMultipleNovelsInfo(
    List<String>? ncodes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMultipleNovelsInfo, [ncodes]),
            returnValue: _i5.Future<Map<String, _i6.NovelInfo>>.value(
              <String, _i6.NovelInfo>{},
            ),
          )
          as _i5.Future<Map<String, _i6.NovelInfo>>);

  @override
  _i5.Future<_i6.NovelInfo> fetchBasicNovelInfo(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBasicNovelInfo, [ncode]),
            returnValue: _i5.Future<_i6.NovelInfo>.value(
              _FakeNovelInfo_23(
                this,
                Invocation.method(#fetchBasicNovelInfo, [ncode]),
              ),
            ),
          )
          as _i5.Future<_i6.NovelInfo>);

  @override
  _i5.Future<List<_i7.Episode>> fetchEpisodeList(String? ncode, int? page) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEpisodeList, [ncode, page]),
            returnValue: _i5.Future<List<_i7.Episode>>.value(<_i7.Episode>[]),
          )
          as _i5.Future<List<_i7.Episode>>);

  @override
  _i5.Future<_i6.NovelInfo> fetchNovelInfo(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNovelInfo, [ncode]),
            returnValue: _i5.Future<_i6.NovelInfo>.value(
              _FakeNovelInfo_23(
                this,
                Invocation.method(#fetchNovelInfo, [ncode]),
              ),
            ),
          )
          as _i5.Future<_i6.NovelInfo>);

  @override
  _i5.Future<_i7.Episode> fetchEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEpisode, [ncode, episode]),
            returnValue: _i5.Future<_i7.Episode>.value(
              _FakeEpisode_24(
                this,
                Invocation.method(#fetchEpisode, [ncode, episode]),
              ),
            ),
          )
          as _i5.Future<_i7.Episode>);

  @override
  _i5.Future<_i8.NovelSearchResult> searchNovels(
    _i14.NovelSearchQuery? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchNovels, [query]),
            returnValue: _i5.Future<_i8.NovelSearchResult>.value(
              _FakeNovelSearchResult_25(
                this,
                Invocation.method(#searchNovels, [query]),
              ),
            ),
          )
          as _i5.Future<_i8.NovelSearchResult>);
}

/// A class which mocks [NovelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNovelRepository extends _i1.Mock implements _i15.NovelRepository {
  MockNovelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Ref get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _i12.dummyValue<_i16.Ref>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i16.Ref);

  @override
  _i9.ApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeApiService_26(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i9.ApiService);

  @override
  _i16.AsyncValue<_i17.AppSettings> get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _i12.dummyValue<_i16.AsyncValue<_i17.AppSettings>>(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i16.AsyncValue<_i17.AppSettings>);

  @override
  _i10.SwrClient get swrClient =>
      (super.noSuchMethod(
            Invocation.getter(#swrClient),
            returnValue: _FakeSwrClient_27(this, Invocation.getter(#swrClient)),
          )
          as _i10.SwrClient);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<_i18.DownloadProgress> watchDownloadProgress(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchDownloadProgress, [ncode]),
            returnValue: _i5.Stream<_i18.DownloadProgress>.empty(),
          )
          as _i5.Stream<_i18.DownloadProgress>);

  @override
  _i5.Future<bool> addNovelToLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#addNovelToLibrary, [ncode]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> removeFromLibrary(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromLibrary, [ncode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addToHistory({
    required String? ncode,
    required String? title,
    required String? writer,
    required int? lastEpisode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addToHistory, [], {
              #ncode: ncode,
              #title: title,
              #writer: writer,
              #lastEpisode: lastEpisode,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteHistory(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHistory, [ncode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> downloadSingleEpisode(
    String? ncode,
    int? episode, {
    String? revised,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadSingleEpisode,
              [ncode, episode],
              {#revised: revised},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i19.NovelContentElement>> getEpisode(
    String? ncode,
    int? episode, {
    String? revised,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEpisode,
              [ncode, episode],
              {#revised: revised},
            ),
            returnValue: _i5.Future<List<_i19.NovelContentElement>>.value(
              <_i19.NovelContentElement>[],
            ),
          )
          as _i5.Future<List<_i19.NovelContentElement>>);

  @override
  _i5.Future<void> downloadEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#downloadEpisode, [ncode, episode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> downloadNovel(String? ncode, int? totalEpisodes) =>
      (super.noSuchMethod(
            Invocation.method(#downloadNovel, [ncode, totalEpisodes]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteDownloadedEpisode(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadedEpisode, [ncode, episode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteDownloadedNovel(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadedNovel, [ncode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<bool> isEpisodeDownloaded(String? ncode, int? episode) =>
      (super.noSuchMethod(
            Invocation.method(#isEpisodeDownloaded, [ncode, episode]),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  _i5.Future<_i11.DownloadResult> downloadNovelWithResult(
    String? ncode,
    int? totalEpisodes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadNovelWithResult, [ncode, totalEpisodes]),
            returnValue: _i5.Future<_i11.DownloadResult>.value(
              _FakeDownloadResult_28(
                this,
                Invocation.method(#downloadNovelWithResult, [
                  ncode,
                  totalEpisodes,
                ]),
              ),
            ),
          )
          as _i5.Future<_i11.DownloadResult>);

  @override
  _i5.Future<List<_i7.Episode>> fetchEpisodeList(String? ncode, int? page) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEpisodeList, [ncode, page]),
            returnValue: _i5.Future<List<_i7.Episode>>.value(<_i7.Episode>[]),
          )
          as _i5.Future<List<_i7.Episode>>);

  @override
  _i5.Stream<_i6.NovelInfo> watchNovelInfo(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchNovelInfo, [ncode]),
            returnValue: _i5.Stream<_i6.NovelInfo>.empty(),
          )
          as _i5.Stream<_i6.NovelInfo>);

  @override
  _i5.Stream<List<_i7.Episode>> watchEpisodeList(String? ncode, int? page) =>
      (super.noSuchMethod(
            Invocation.method(#watchEpisodeList, [ncode, page]),
            returnValue: _i5.Stream<List<_i7.Episode>>.empty(),
          )
          as _i5.Stream<List<_i7.Episode>>);

  @override
  _i5.Stream<int?> watchLastReadEpisode(String? ncode) =>
      (super.noSuchMethod(
            Invocation.method(#watchLastReadEpisode, [ncode]),
            returnValue: _i5.Stream<int?>.empty(),
          )
          as _i5.Stream<int?>);
}
