// Mocks generated by Mockito 5.4.6 from annotations
// in novelty/test/services/narou_auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:novelty/repositories/auth_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveNarouid(String? narouid) =>
      (super.noSuchMethod(
            Invocation.method(#saveNarouid, [narouid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getNarouid() =>
      (super.noSuchMethod(
            Invocation.method(#getNarouid, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> saveUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#saveUsername, [username]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getUsername() =>
      (super.noSuchMethod(
            Invocation.method(#getUsername, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> saveSessionCookies({
    required String? ks2,
    required String? ses,
    required String? userl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveSessionCookies, [], {
              #ks2: ks2,
              #ses: ses,
              #userl: userl,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String>?> getSessionCookies() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionCookies, []),
            returnValue: _i3.Future<Map<String, String>?>.value(),
          )
          as _i3.Future<Map<String, String>?>);

  @override
  _i3.Future<bool> hasSessionCookies() =>
      (super.noSuchMethod(
            Invocation.method(#hasSessionCookies, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> buildCookieHeader() =>
      (super.noSuchMethod(
            Invocation.method(#buildCookieHeader, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
