// Mocks generated by Mockito 5.4.6 from annotations
// in novelty/test/screens/novel_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:kakuyomu_parser/kakuyomu_parser.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:novelty/models/download_progress.dart' as _i9;
import 'package:novelty/models/download_result.dart' as _i3;
import 'package:novelty/models/episode.dart' as _i12;
import 'package:novelty/models/novel_info.dart' as _i13;
import 'package:novelty/repositories/novel_repository.dart' as _i4;
import 'package:novelty/services/api_service.dart' as _i2;
import 'package:novelty/sites/novel_source.dart' as _i10;
import 'package:novelty/utils/settings_provider.dart' as _i7;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDownloadResult_1 extends _i1.SmartFake
    implements _i3.DownloadResult {
  _FakeDownloadResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NovelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNovelRepository extends _i1.Mock implements _i4.NovelRepository {
  MockNovelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Ref get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _i6.dummyValue<_i5.Ref>(this, Invocation.getter(#ref)),
          )
          as _i5.Ref);

  @override
  _i2.ApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeApiService_0(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i2.ApiService);

  @override
  _i5.AsyncValue<_i7.AppSettings> get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _i6.dummyValue<_i5.AsyncValue<_i7.AppSettings>>(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i5.AsyncValue<_i7.AppSettings>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Stream<_i9.DownloadProgress> watchDownloadProgress(
    _i10.NovelSource? source,
    String? workId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchDownloadProgress, [source, workId]),
            returnValue: _i8.Stream<_i9.DownloadProgress>.empty(),
          )
          as _i8.Stream<_i9.DownloadProgress>);

  @override
  _i8.Future<bool> addNovelToLibrary(
    _i10.NovelSource? source,
    String? workId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addNovelToLibrary, [source, workId]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> removeFromLibrary(
    _i10.NovelSource? source,
    String? workId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromLibrary, [source, workId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> refreshStaleLibraryMetadata({
    Duration? staleAfter = const Duration(hours: 6),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshStaleLibraryMetadata, [], {
              #staleAfter: staleAfter,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addToHistory({
    required _i10.NovelSource? source,
    required String? workId,
    required String? title,
    required String? writer,
    required int? lastEpisode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addToHistory, [], {
              #source: source,
              #workId: workId,
              #title: title,
              #writer: writer,
              #lastEpisode: lastEpisode,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateReadingProgress({
    required _i10.NovelSource? source,
    required String? workId,
    required String? title,
    required String? writer,
    required int? episode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateReadingProgress, [], {
              #source: source,
              #workId: workId,
              #title: title,
              #writer: writer,
              #episode: episode,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteHistory(_i10.NovelSource? source, String? workId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHistory, [source, workId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> downloadSingleEpisode(
    _i10.NovelSource? source,
    String? workId,
    int? episode, {
    String? revised,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadSingleEpisode,
              [source, workId, episode],
              {#revised: revised},
            ),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<List<_i11.NovelContentElement>> getEpisode(
    _i10.NovelSource? source,
    String? workId,
    int? episode, {
    String? revised,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEpisode,
              [source, workId, episode],
              {#revised: revised},
            ),
            returnValue: _i8.Future<List<_i11.NovelContentElement>>.value(
              <_i11.NovelContentElement>[],
            ),
          )
          as _i8.Future<List<_i11.NovelContentElement>>);

  @override
  _i8.Future<void> downloadEpisode(
    _i10.NovelSource? source,
    String? workId,
    int? episode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadEpisode, [source, workId, episode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> downloadNovel(
    _i10.NovelSource? source,
    String? workId,
    int? totalEpisodes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadNovel, [source, workId, totalEpisodes]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteDownloadedEpisode(
    _i10.NovelSource? source,
    String? workId,
    int? episode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadedEpisode, [
              source,
              workId,
              episode,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteDownloadedNovel(
    _i10.NovelSource? source,
    String? workId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDownloadedNovel, [source, workId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<bool> isEpisodeDownloaded(
    _i10.NovelSource? source,
    String? workId,
    int? episode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isEpisodeDownloaded, [source, workId, episode]),
            returnValue: _i8.Stream<bool>.empty(),
          )
          as _i8.Stream<bool>);

  @override
  _i8.Future<_i3.DownloadResult> downloadNovelWithResult(
    _i10.NovelSource? source,
    String? workId,
    int? totalEpisodes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#downloadNovelWithResult, [
              source,
              workId,
              totalEpisodes,
            ]),
            returnValue: _i8.Future<_i3.DownloadResult>.value(
              _FakeDownloadResult_1(
                this,
                Invocation.method(#downloadNovelWithResult, [
                  source,
                  workId,
                  totalEpisodes,
                ]),
              ),
            ),
          )
          as _i8.Future<_i3.DownloadResult>);

  @override
  _i8.Future<List<_i12.Episode>> fetchEpisodeList(
    _i10.NovelSource? source,
    String? workId,
    int? page,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEpisodeList, [source, workId, page]),
            returnValue: _i8.Future<List<_i12.Episode>>.value(<_i12.Episode>[]),
          )
          as _i8.Future<List<_i12.Episode>>);

  @override
  _i8.Stream<_i13.NovelInfo> watchNovelInfo(
    _i10.NovelSource? source,
    String? workId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchNovelInfo, [source, workId]),
            returnValue: _i8.Stream<_i13.NovelInfo>.empty(),
          )
          as _i8.Stream<_i13.NovelInfo>);

  @override
  _i8.Future<void> refreshNovelInfo(_i10.NovelSource? source, String? workId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshNovelInfo, [source, workId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<List<_i12.Episode>> watchEpisodeList(
    _i10.NovelSource? source,
    String? workId,
    int? page,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchEpisodeList, [source, workId, page]),
            returnValue: _i8.Stream<List<_i12.Episode>>.empty(),
          )
          as _i8.Stream<List<_i12.Episode>>);

  @override
  _i8.Future<void> refreshEpisodeList(
    _i10.NovelSource? source,
    String? workId,
    int? page,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshEpisodeList, [source, workId, page]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<int?> watchLastReadEpisode(
    _i10.NovelSource? source,
    String? workId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchLastReadEpisode, [source, workId]),
            returnValue: _i8.Stream<int?>.empty(),
          )
          as _i8.Stream<int?>);
}
